use_frameworks!

target 'AHContainerViewController_Example' do
  pod 'AHContainerViewController', :path => '../'

  target 'AHContainerViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
